name: DEV Branches CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Test
        uses: vitorsm/python-test-action@master
        with:
          deps_list: '../../requirements.txt'
          path: './my_home_server/tests/'
          test_dir: '.'
          pattern: 'test_*.py'
          python_path: '../../'

  upload-coverage-data:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      PYTHON: '3.8'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Generate coverage report
        run: |
          pip3 install coverage
          pip3 install -r requirements.txt
          cd my_home_server/tests/
          sudo mkdir /var/log/myhome-server
          sudo chmod 777 /var/log/myhome-server
          PYTHONPATH=../../ coverage run --branch --source=../ --omit=./* -m unittest discover -s .
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unit-integ-tests
          name: upload-coverage-data
          path_to_write_report: ./coverage/codecov_report.gz
